
// This file was auto-generated by ML.NET Model Builder. 

using MLModel_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel.ModelInput sampleData = new MLModel.ModelInput()
{
    Idcomida = 5F,
    Idusuario = @"4d21e431-b17a-4d00-8543-84a0496fdcd3",
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Rating with predicted Rating from sample data...\n\n");


Console.WriteLine($"Idcomida: {5F}");
Console.WriteLine($"Idusuario: {@"4d21e431-b17a-4d00-8543-84a0496fdcd3"}");
Console.WriteLine($"Rating: {0F}");


Console.WriteLine($"\n\nPredicted Rating: {predictionResult.Score}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

